Implemented the init script actions.
--HG--
branch : feature/init-script

diff --git a/lsb/xllmnrd.in b/lsb/xllmnrd.in
--- a/lsb/xllmnrd.in
+++ b/lsb/xllmnrd.in
@@ -18,7 +18,8 @@
 ### END INIT INFO
 
 DAEMON=@sbindir@/xllmnrd
-DAEMON_ARGS=''
+USER=xllmnrd
+PIDDIR=/var/run/xllmnrd
 
 if [ ! -x $DAEMON ]; then
     exit 0
@@ -26,21 +27,52 @@ fi
 
 . /lib/lsb/init-functions
 
-log_warning_msg $0 is a placeholder script
-
 case "$1" in
 start)
-    start_daemon /bin/su - daemon -c "$DAEMON $DAEMON_ARGS"
+    if [ ! -d $PIDDIR ]; then
+        rm -f $PIDDIR
+        mkdir $PIDDIR
+        chown $USER $PIDDIR
+    fi
+    # A start failure is expected on Debian-based systems if another daemon is
+    # already running.  See issue #31.
+    if start_daemon -p $PIDDIR/xllmnrd.pid /bin/su - $USER \
+        -s /bin/sh -c "$DAEMON -p $PIDDIR/xllmnrd.pid"; then
+        log_success_msg "Started $DAEMON"
+    else
+        status=$?
+        log_failure_msg "Failed to start $DAEMON"
+        exit $status
+    fi
     ;;
 stop)
-    #killproc -p /var/run/xllmnrd/xllmnrd.pid $DAEMON
-    killall -- $DAEMON
+    if killproc -p $PIDDIR/xllmnrd.pid $DAEMON; then
+        log_success_msg "Stopped $DAEMON"
+    else
+        status=$?
+        log_failuer_msg "Failed to stop $DAEMON"
+        exit $status
+    fi
     ;;
 restart|force-reload)
     $0 stop
     $0 start
     ;;
 status)
+    pid=$(pidofproc -p $PIDDIR/xllmnrd.pid $DAEMON)
+    status=$?
+    if [ $status -eq 0 ]; then
+        echo "$DAEMON is running"
+    elif [ $status -eq 3 ]; then
+        echo "$DAEMON is not running"
+    else
+        log_failure_msg "Failed to get status of $DAEMON"
+    fi
+    exit $status
+    ;;
+*)
+    echo "Usage: $@ {start|stop|restart|force-reload|status}" >&2
+    exit 3
     ;;
 esac
 
